# Generated by Django 6.0.5 on 2026-05-13 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TierConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_padrao', models.CharField(choices=[('flash', 'Flash (Econômico)'), ('pro', 'Pro (Avançado)'), ('max', 'Máximo (Todas as fases)')], default='flash', max_length=20, verbose_name='Nível padrão de IA')),
            ],
            options={
                'verbose_name': 'Nível de IA (Global)',
                'verbose_name_plural': 'Nível de IA (Global)',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plano', models.CharField(choices=[('basic', 'Básico'), ('pro', 'Profissional')], max_length=20)),
                ('creditos_base', models.IntegerField()),
                ('creditos_bonus', models.IntegerField(default=0)),
                ('data_inicio', models.DateTimeField()),
                ('data_expiracao', models.DateTimeField()),
                ('stripe_session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clerk_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('is_pro', models.BooleanField(default=False)),
                ('credits', models.IntegerField(default=5)),
                ('subscription_status', models.CharField(default='inactive', max_length=50)),
                ('subscription_start_at', models.DateTimeField(blank=True, null=True)),
                ('subscription_expires_at', models.DateTimeField(blank=True, null=True)),
                ('has_seen_tour', models.BooleanField(default=False)),
                ('can_view_global_stats', models.BooleanField(default=False, verbose_name='Ver Painel Global')),
                ('tier', models.CharField(blank=True, choices=[('', 'Usar padrão global'), ('flash', 'Flash (Econômico)'), ('pro', 'Pro (Avançado)'), ('max', 'Máximo (Todas as fases)')], default='', max_length=20, verbose_name='Nível de IA')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
            },
        ),
    ]
