# Generated by Django 6.0.5 on 2026-05-22 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TermoAceite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.CharField(default='1.0', max_length=20)),
                ('aceito_em', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termos_aceitos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aceite de Termos',
                'verbose_name_plural': 'Aceites de Termos',
                'ordering': ['-aceito_em'],
                'unique_together': {('user', 'versao')},
            },
        ),
    ]
