# Generated by Django 5.2.14 on 2026-05-24 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_termo_aceite'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='forum_last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
