# Generated by Django 5.2.14 on 2026-05-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_forum_last_seen_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='creditos_infinitos',
            field=models.BooleanField(default=False, verbose_name='Créditos infinitos'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='credits',
            field=models.IntegerField(default=5, verbose_name='Créditos'),
        ),
    ]
