# Generated by Django 6.0.5 on 2026-05-13 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CacheTese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(max_length=255, unique=True)),
                ('vertex_resultado', models.TextField()),
                ('perplexity_resultado', models.TextField()),
                ('tipo_infracao', models.CharField(blank=True, db_index=True, max_length=50)),
                ('hit_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cache de Tese',
                'verbose_name_plural': 'Cache de Teses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoParecer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabecalho_imagem', models.ImageField(blank=True, help_text='Banner completo (PNG/JPG) com proporção wide.', null=True, upload_to='assets/logos/')),
                ('rodape_deferido', models.TextField(help_text='HTML para caso de Deferimento')),
                ('rodape_indeferido', models.TextField(help_text='HTML para caso de Indeferimento')),
            ],
            options={
                'verbose_name': 'Configuração do Parecer',
                'verbose_name_plural': 'Configurações do Parecer',
            },
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('posicao', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pastas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['posicao', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pa', models.CharField(blank=True, max_length=100, verbose_name='Processo Administrativo')),
                ('sgpe', models.CharField(blank=True, max_length=100, verbose_name='SGPE')),
                ('recorrente', models.CharField(blank=True, max_length=255)),
                ('data_sessao', models.DateField(blank=True, null=True, verbose_name='Data da Sessão')),
                ('prazo_final', models.DateField(blank=True, null=True, verbose_name='Prazo Final Recurso JARI')),
                ('data_protocolo', models.DateField(blank=True, null=True, verbose_name='Data Protocolo Recurso JARI')),
                ('paginas_defesa', models.CharField(blank=True, max_length=100, verbose_name='Páginas da Defesa')),
                ('fase', models.CharField(choices=[('identificacao', '1. Identificação'), ('documentos', '2. Documentos'), ('documentos_extraindo', '2. Documentos (extraindo)'), ('admissibilidade', '3. Admissibilidade'), ('admissibilidade_aguardando', '3. Admissibilidade (aguardando)'), ('tese', '4. Tese'), ('tese_aguardando', '4. Tese (aguardando)'), ('parecer', '5. Parecer'), ('parecer_gerando', '5. Parecer (gerando)'), ('auditoria', '6. Auditoria'), ('finalizado', 'Finalizado')], db_index=True, default='identificacao', max_length=30)),
                ('resultado_final', models.CharField(blank=True, choices=[('DEFERIDO', 'Deferido'), ('INDEFERIDO', 'Indeferido')], db_index=True, max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pasta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos', to='pareceres.pasta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Parecer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_ia', models.TextField(blank=True)),
                ('provider', models.CharField(blank=True, max_length=20)),
                ('texto_editado', models.TextField(blank=True)),
                ('blindagem_score', models.IntegerField(blank=True, null=True)),
                ('blindagem_detalhes', models.TextField(blank=True)),
                ('checklist_auditoria', models.JSONField(blank=True, null=True)),
                ('feedback_score', models.IntegerField(blank=True, null=True)),
                ('feedback_tags', models.CharField(blank=True, max_length=500)),
                ('feedback_notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parecer', to='pareceres.processo')),
            ],
            options={
                'verbose_name': 'Parecer',
                'verbose_name_plural': 'Pareceres',
            },
        ),
        migrations.CreateModel(
            name='AnaliseTese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField(default=1)),
                ('titulo', models.CharField(max_length=500)),
                ('fundamentacao', models.TextField(blank=True)),
                ('acolhida', models.BooleanField(blank=True, null=True)),
                ('vertex_resultado', models.TextField(blank=True)),
                ('perplexity_resultado', models.TextField(blank=True)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teses', to='pareceres.processo')),
            ],
            options={
                'verbose_name': 'Análise de Tese',
                'verbose_name_plural': 'Análises de Teses',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Admissibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_infracao', models.DateField(blank=True, null=True)),
                ('data_infracao_fallback', models.BooleanField(default=False)),
                ('data_totalizacao_pontos', models.DateField(blank=True, null=True)),
                ('data_conclusao_multa', models.DateField(blank=True, null=True)),
                ('data_conhecimento_infracao', models.DateField(blank=True, null=True)),
                ('tipo_penalidade', models.CharField(blank=True, choices=[('multa', 'Multa'), ('advertencia', 'Advertência'), ('suspensao', 'Suspensão'), ('cassacao', 'Cassação')], max_length=20)),
                ('tem_flagrante', models.BooleanField(blank=True, null=True)),
                ('is_tempestivo', models.BooleanField(blank=True, null=True)),
                ('has_prescricao_punitiva', models.BooleanField(blank=True, null=True)),
                ('has_prescricao_intercorrente', models.BooleanField(blank=True, null=True)),
                ('has_decadencia', models.BooleanField(blank=True, null=True)),
                ('julgador_tempestivo', models.BooleanField(blank=True, null=True)),
                ('julgador_prescricao_punitiva', models.BooleanField(blank=True, null=True)),
                ('julgador_prescricao_intercorrente', models.BooleanField(blank=True, null=True)),
                ('julgador_decadencia', models.BooleanField(blank=True, null=True)),
                ('texto_resultado', models.TextField(blank=True, help_text='Texto completo da análise de admissibilidade')),
                ('tabela_datas_sensiveis', models.TextField(blank=True)),
                ('infracao_documento', models.CharField(blank=True, max_length=255)),
                ('processo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admissibilidade', to='pareceres.processo')),
            ],
            options={
                'verbose_name': 'Admissibilidade',
                'verbose_name_plural': 'Admissibilidades',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('autuacao', 'Autuação'), ('consolidado', 'Consolidado'), ('ata', 'Ata de Julgamento')], max_length=20)),
                ('arquivo', models.FileField(upload_to='uploads/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('extracao_json', models.JSONField(blank=True, null=True)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='pareceres.processo')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'unique_together': {('processo', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('categoria', models.CharField(choices=[('fase', 'Transição de Fase'), ('ia_request', 'Requisição IA'), ('erro', 'Erro'), ('decisao', 'Decisão do Julgador'), ('upload', 'Upload de Documento'), ('credito', 'Crédito Consumido')], db_index=True, max_length=20)),
                ('fase', models.CharField(blank=True, max_length=30)),
                ('dados', models.JSONField(blank=True, default=dict)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('latency_ms', models.IntegerField(default=0)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('processo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='pareceres.processo')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['categoria', 'timestamp'], name='pareceres_a_categor_63dc36_idx'), models.Index(fields=['user', 'timestamp'], name='pareceres_a_user_id_29c062_idx'), models.Index(fields=['provider', '-timestamp'], name='pareceres_a_provide_2291aa_idx')],
            },
        ),
    ]
