# Generated by Django 6.0.5 on 2026-05-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pareceres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissibilidade',
            name='has_prescricao_intercorrente_bienal',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admissibilidade',
            name='julgador_prescricao_intercorrente_bienal',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
