# Generated by Django 6.0.5 on 2026-05-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pareceres', '0002_add_prescricao_intercorrente_bienal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='fase',
            field=models.CharField(choices=[('documentos', '1. Documentos'), ('documentos_extraindo', '1. Documentos (extraindo)'), ('documentos_extraidos', '2. Dados Extraídos'), ('admissibilidade', '3. Admissibilidade'), ('admissibilidade_aguardando', '3. Admissibilidade (aguardando)'), ('tese', '4. Tese'), ('tese_aguardando', '4. Tese (aguardando)'), ('parecer', '5. Parecer'), ('parecer_gerando', '5. Parecer (gerando)'), ('auditoria', '6. Auditoria'), ('finalizado', 'Finalizado')], db_index=True, default='documentos', max_length=30),
        ),
    ]
