# Generated by Django 6.0.5 on 2026-05-22 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pareceres', '0003_alter_processo_fase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, help_text='Chave de sessão para processos anônimos (sem login).', max_length=40),
        ),
        migrations.AlterField(
            model_name='processo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BancoTese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('conteudo', models.TextField()),
                ('tipo_infracao', models.CharField(blank=True, db_index=True, max_length=100)),
                ('is_public', models.BooleanField(db_index=True, default=False)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banco_teses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tese (Banco)',
                'verbose_name_plural': 'Teses (Banco)',
                'ordering': ['-usage_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Usuário'), ('assistant', 'Assistente')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='pareceres.processo')),
            ],
            options={
                'verbose_name': 'Mensagem do Chat',
                'verbose_name_plural': 'Mensagens do Chat',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoNormativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arquivo', models.CharField(db_index=True, max_length=500)),
                ('pagina_inicio', models.IntegerField(default=1)),
                ('texto', models.TextField()),
                ('embedding', models.JSONField(blank=True, help_text='Vetor de embedding (float list) — gerado por sentence-transformers.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Documento Normativo',
                'verbose_name_plural': 'Documentos Normativos',
                'ordering': ['nome_arquivo', 'pagina_inicio'],
                'indexes': [models.Index(fields=['nome_arquivo', 'pagina_inicio'], name='pareceres_d_nome_ar_6a5032_idx')],
            },
        ),
        migrations.CreateModel(
            name='PostForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('conteudo', models.TextField()),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curtidas', models.ManyToManyField(blank=True, related_name='posts_curtidos', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_forum', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post do Fórum',
                'verbose_name_plural': 'Posts do Fórum',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_forum', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='pareceres.postforum')),
            ],
            options={
                'verbose_name': 'Comentário do Fórum',
                'verbose_name_plural': 'Comentários do Fórum',
                'ordering': ['created_at'],
            },
        ),
    ]
