# Generated by Django 6.0.5 on 2026-05-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pareceres', '0004_add_forum_banco_normativo_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissibilidade',
            name='data_instauracao',
            field=models.DateField(blank=True, help_text='Instauração do processo', null=True),
        ),
        migrations.AddField(
            model_name='admissibilidade',
            name='data_na',
            field=models.DateField(blank=True, help_text='Notificação de Autuação', null=True),
        ),
        migrations.AddField(
            model_name='admissibilidade',
            name='data_np',
            field=models.DateField(blank=True, help_text='Notificação de Penalidade', null=True),
        ),
    ]
