# Generated by Django 5.2.14 on 2026-05-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pareceres', '0005_admissibilidade_data_instauracao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissibilidade',
            name='fundamentacoes',
            field=models.JSONField(blank=True, default=dict, help_text='Fundamentação individual por critério {tempestivo, punitiva, intercorrente, bienal, decadencia}'),
        ),
    ]
