# Generated by Django 5.2.14 on 2026-05-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pareceres', '0006_admissibilidade_fundamentacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='resultado_final',
            field=models.CharField(blank=True, choices=[('DEFERIDO', 'Deferido'), ('INDEFERIDO', 'Indeferido'), ('NAO_CONHECIDO', 'Não Conhecido')], db_index=True, max_length=15),
        ),
    ]
