# Generated by Django 6.0.5 on 2026-06-21 17:10

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('pareceres', '0007_alter_processo_resultado_final'),
    ]

    operations = [
        VectorExtension(),
        # jsonb não casteia direto para vector. Como a tabela está vazia
        # (RAG nunca foi populado — nem local nem prod), trocamos o tipo com
        # USING NULL. ATENÇÃO: se algum dia houver dados, migrar antes.
        migrations.RunSQL(
            sql='ALTER TABLE pareceres_documentonormativo '
                'ALTER COLUMN embedding TYPE vector(384) USING NULL;',
            reverse_sql='ALTER TABLE pareceres_documentonormativo '
                        'ALTER COLUMN embedding TYPE jsonb USING NULL;',
            state_operations=[
                migrations.AlterField(
                    model_name='documentonormativo',
                    name='embedding',
                    field=pgvector.django.vector.VectorField(blank=True, dimensions=384, help_text='Vetor de embedding (pgvector) — gerado por sentence-transformers.', null=True),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name='documentonormativo',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='docnorm_emb_hnsw', opclasses=['vector_cosine_ops']),
        ),
    ]
