# Generated by Django 5.2.16 on 2026-07-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pareceres', '0008_alter_documentonormativo_embedding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='relatorio_sintese_editada',
            field=models.TextField(blank=True, default=''),
        ),
    ]
